


[[redirects]]

from = "/sq/*"
to = "sq/404"
status = 404


[[redirects]]

from = "/en/*"
to = "en/404"
status = 404


[[redirects]]

from = "/tr/*"
to = "tr/404"
status = 404



  
[[redirects]]
  from = "/*"
  to = "/a"
  status = 302
  conditions = {Role = ["Everyone"]}

  
[[redirects]]
  from = "/*"
  to = "/:*"
  status = 302
  conditions = {Role = ["Everyone"]}


    





