[[redirects]]

from = "/sq/*"
to = "sq/404"
status = 404


[[redirects]]

from = "/en/*"
to = "en/404"
status = 404


[[redirects]]

from = "/tr/*"
to = "tr/404"
status = 404


[[redirects]]

from = "/"
to = "/404"
status = 200


[[redirects]]

from = "/"
to = "/404"
status = 404


