


[[redirects]]

from = "/sq/*"
to = "sq/404"
status = 404


[[redirects]]

from = "/en/*"
to = "en/404"
status = 404


[[redirects]]

from = "/tr/*"
to = "tr/404"
status = 404



[[redirects]]
  from = "/*:splat"
  to = "/sq"
  status = 200
  conditions = {Role = ["Everyone"]}


[[redirects]]
  from = "/*:splat"
  to = "/sq"
  status = 404
  conditions = {Role = ["Everyone"]}


[[redirects]]
  from = "/_next/*"
  to = "/:splat"
  status = 200
  conditions = {Role = ["Everyone"]}



[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200
