[[redirects]]

from = "/sq/*"
to = "sq/not-found"
status = 404


[[redirects]]

from = "/en/*"
to = "en/not-found"
status = 404


[[redirects]]

from = "/tr/*"
to = "tr/not-found"
status = 404


[[redirects]]

from = "/*"
to = "/not-found"
status = 404