


[[redirects]]

from = "/sq/*"
to = "sq/404"
status = 404


[[redirects]]

from = "/en/*"
to = "en/404"
status = 404


[[redirects]]

from = "/tr/*"
to = "tr/404"
status = 404



[[redirects]]
  from = "/*"
  to = "/sq"
  status = 200
  conditions = {Role = ["Everyone"]}

  
[[redirects]]
  from = "/*"
  to = "/sq"
  status = 302
  conditions = {Role = ["Everyone"]}


[[redirects]]
  from = "/*"
  to = "/sq"
  status = 404
  conditions = {Role = ["Everyone"]}


[[redirects]]
  from = "/_next/*"
  to = "/"
  status = 200
  conditions = {Role = ["Everyone"]}

  
[[redirects]]
  from = "/_next/*"
  to = "/404"
  status = 404
  conditions = {Role = ["Everyone"]}



[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200
