


[[redirects]]

from = "/sq/*"
to = "sq/404"
status = 404


[[redirects]]

from = "/en/*"
to = "en/404"
status = 404


[[redirects]]

from = "/tr/*"
to = "tr/404"
status = 404


[[redirects]]

from = "/"
to = "/sq"
status = 302

[[redirects]]

from = "/*"
to = "/sq/:splat"
status = 302

[[redirects]]

from = "/*"
to = "/sq/404"
status = 302








